name: Build container images

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false
      tag:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: "${{ matrix.image }}"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        image:
          - "skopeo_cidev"
          - "podman_cidev"
        include:
          - image: skopeo_cidev
            context: container-images/skopeo_cidev
            file: container-images/skopeo_cidev/Containerfile
          - image: podman_cidev
            context: .
            file: container-images/podman_cidev/Containerfile
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ inputs.tag }}
      CONTEXT: ${{ matrix.context }}
      CONTAINERFILE: ${{ matrix.file }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build image
        run: podman build -t "$IMAGE" -f "$CONTAINERFILE" "$CONTEXT"

      - name: Log in to ghcr.io
        if: ${{ inputs.push }}
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$REGISTRY_PASSWORD" | podman login ghcr.io -u "$REGISTRY_USER" --password-stdin

      - name: Push image
        if: ${{ inputs.push }}
        run: podman push "$IMAGE"
